# 2.1 理解Python中的数据类型

## 2.1.1 Python整型不仅仅是一个整型

在python中定义一个整型，例如x=10000时，x并不是一个“原生”整型，而是一个指针，指向一个C语言的复合结构体。如下：
```c
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
}
```

## 2.1.2 Python列表不仅仅是一个列表

创建一个整型值列表

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

或者创建一个字符串列表

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

创建一个异构的列表

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## 2.1.3 Python中的固定类型数组

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2.1.4 从Python列表创建数组

创建ndarray整型数组

In [7]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

> NumPy要求数组必须包含同一类型的数据，如果类型不匹配，NumPy将会向上转换（如果可行）

In [8]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

可以使用dtype明确设数组的数据类型

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

NumPy数组可以被指定为多维的

In [10]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 2.1.5 从头创建数组

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3, 3))

array([[0.11953137, 0.2310201 , 0.94412494],
       [0.73295003, 0.5843912 , 0.86275254],
       [0.824946  , 0.7499389 , 0.23526971]])

In [17]:
np.random.normal(0, 1, (3, 3))

array([[ 2.14312857,  1.48529496,  0.49908368],
       [ 2.26417618,  0.43870319,  1.03435892],
       [ 0.64319073, -0.10476116,  1.23928368]])

In [18]:
np.random.randint(0, 10, (3, 3))

array([[0, 2, 1],
       [3, 5, 1],
       [9, 7, 2]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.empty(3)

array([1., 1., 1.])

## 2.1.6 NumPy标准数据类型

> bool_, int_, intc, intp, int8, int16, int32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, complex64, complex128