# 2.2.1 NumPy数组的属性

In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

## 每个数组有ndim（数组的维度）、shape（数组每个维度的大小）和size（数组的总大小）属性

In [5]:
x3.ndim

3

In [6]:
x3.shape

(3, 4, 5)

In [7]:
x3.size

60

## dtype（数组的数据类型）

In [8]:
x3.dtype

dtype('int64')

## itemsize（每个数组元素字节大小）8bytes，以及表示数组总字节大小的属性nbytes

In [9]:
x3.itemsize

8

In [10]:
x3.nbytes

480

> 一般来说，我们可以认为nbytes等于itemsize和size的乘积大小。

# 2.2.2 数组索引：获取单个元素

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

In [13]:
x1[4]

7

In [14]:
x1[-1]

9

In [15]:
x1[-2]

7

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x2[0, 0]

3

In [18]:
x2[2, -1]

7

In [19]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [20]:
x1[0] = 3.14159 # 这将被截断，因为numpy的数组是固定类型的
x1

array([3, 0, 3, 3, 7, 9])

# 2.2.3 数组切片：获取子数组

1. 一维子数组

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [23]:
x[5:] # 索引5之后的元素

array([5, 6, 7, 8, 9])

In [24]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [25]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [26]:
x[1::2] # 每隔一个元素，索引从1开始

array([1, 3, 5, 7, 9])

In [27]:
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

2. 多维子数组

In [29]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [30]:
x2[:2, :3] # 两行，三列

array([[12,  5,  2],
       [ 7,  6,  8]])

In [31]:
x2[:3, ::2] # 所有行，每隔一列

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [32]:
x2[::-1, ::-1] # 逆序

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

3. 获取数组的行和列

In [33]:
x2[:, 0] # x2的第一列

array([12,  7,  1])

In [34]:
x2[0, :] # x2的第一行

array([12,  5,  2,  4])

In [35]:
x2[0] # 省略空的切片，效果与上一行

array([12,  5,  2,  4])

4. 非副本视图的子数组

In [36]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [37]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [38]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [39]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

可以看到，修改子数组，原始数组也被修改了。这是因为处理非常大的数据集时，可以获取或处理这些数据集的片段，而不用复制底层的数据缓存。

5. 创建数组的副本

In [40]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [41]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [42]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## 2.2.4 数组的变形

In [43]:
grid = np.arange(1, 10).reshape((3, 3)) # reshape返回的也是非副本视图，修改了元素则会影响本来的数据
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [45]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [46]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [47]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 2.2.5 数组拼接和分裂

1. 数组的拼接

In [48]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [49]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [50]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [53]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

2. 数组的分裂

In [54]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [55]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
upper, lower = np.vsplit(grid, [2])
upper, lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [57]:
left, right = np.hsplit(grid, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))