## 2.3.1 缓慢的循环

对数组的每个元素求倒数

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.35 s ± 182 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


这里处理的瓶颈并不是运算本身，而是Cpython在每次循环时必须做数据类型的检查和函数的调度。每次进行倒数运算时，Python首先检查对象的类型，并且动态查找可以使用该数据类型的正确函数。

## 2.3.2 通用函数介绍

NumPy为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，也被称作**向量**操作。

In [3]:
1.0/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
%timeit (1.0 / big_array)

1.23 ms ± 31.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


NumPy中的向量操作是通过**通用函数**实现的。前面我们看过了标量和数组的运算，但是也可以对两个数组进行运算。

In [5]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

多维数组的运算

In [6]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## 2.3.3 探索NumPy的通用函数

1. 数组的运算

In [7]:
x = np.arange(4)

In [8]:
x

array([0, 1, 2, 3])

In [9]:
x + 5

array([5, 6, 7, 8])

In [10]:
x - 5

array([-5, -4, -3, -2])

In [11]:
x * 2

array([0, 2, 4, 6])

In [12]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [13]:
x // 2

array([0, 0, 1, 1])

In [14]:
-x

array([ 0, -1, -2, -3])

In [15]:
x ** 2

array([0, 1, 4, 9])

In [16]:
x % 2

array([0, 1, 0, 1])

In [17]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [18]:
np.add(x, 2)

array([2, 3, 4, 5])

2. 绝对值

In [19]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [20]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [21]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [22]:
# 处理负数
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

3. 三角函数

In [23]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [24]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [25]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [26]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [27]:
x = [-1, 0, 1]
x

[-1, 0, 1]

In [28]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [29]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [30]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

4. 指数和对数

In [31]:
x = [1, 2, 3]
x

[1, 2, 3]

In [32]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
np.exp2(x)

array([2., 4., 8.])

In [34]:
np.power(3, x)

array([ 3,  9, 27])

In [35]:
x = [1, 2, 4, 10]
x

[1, 2, 4, 10]

In [36]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [37]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [38]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

In [39]:
# 还有一些对非常小的输入值可以保持较好的精度
x = [0, 0.001, 0.01, 0.1]
np.expm1(x) # exp(x) - 1

array([0.        , 0.0010005 , 0.01005017, 0.10517092])

In [40]:
np.log1p(x) # log(1 + x)

array([0.        , 0.0009995 , 0.00995033, 0.09531018])

5. 专用的通用函数

In [41]:
from scipy import special
x = [1, 5, 10]
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [42]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [43]:
special.beta(x, 2)

array([0.5       , 0.03333333, 0.00909091])

In [44]:
x = np.array([0, 0.3, 0.7, 1.0])
special.erf(x)

array([0.        , 0.32862676, 0.67780119, 0.84270079])

In [45]:
special.erfc(x)

array([1.        , 0.67137324, 0.32219881, 0.15729921])

In [46]:
special.erfinv(x)

array([0.        , 0.27246271, 0.73286908,        inf])

## 2.3.4 高级的通用函数特性

1. 指定输出

In [47]:
x = np.arange(5)
y = np.arange(5)
np.multiply(x, 10, out=y)
y

array([ 0, 10, 20, 30, 40])

In [48]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

2. 聚合

In [49]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [50]:
np.multiply.reduce(x)

120

In [51]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [52]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

3. 外积

In [53]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])