# 2.4.1 数组值求和

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

49.088985138127555

In [3]:
np.sum(L)

49.088985138127555

NumPy的sum函数更快

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

329 ms ± 26.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
415 µs ± 14.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# 2.4.2 最小值和最大值

In [5]:
min(big_array), max(big_array)

(1.8021916612376288e-06, 0.9999982784937079)

In [6]:
np.min(big_array), np.max(big_array)

(1.8021916612376288e-06, 0.9999982784937079)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

198 ms ± 5.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
440 µs ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
big_array.min(), big_array.max(), big_array.sum()

(1.8021916612376288e-06, 0.9999982784937079, 499814.4738500552)

## 1. 多维度聚合

In [9]:
M = np.random.random((3, 4))
M

array([[0.31635523, 0.20443503, 0.53612265, 0.27072035],
       [0.46496667, 0.18079818, 0.34423145, 0.70119736],
       [0.11230549, 0.66617357, 0.06172077, 0.75978128]])

In [10]:
M.sum()

4.618808041307571

In [11]:
M.min(axis=0)

array([0.11230549, 0.18079818, 0.06172077, 0.27072035])

In [12]:
M.max(axis=1)

array([0.53612265, 0.70119736, 0.75978128])

## 2. 其他聚合函数

| 函数名称 | NaN安全版本 | 描述 |
| -- | -- | -- |
| np.sum | np.nansum | 计算元素的和 |
| np.prod | np.nanprod | 计算元素的积 |
| np.mean | np.nanmean | 计算元素的平均值 |
| np.std | np.nanstd | 计算元素的标准差 |
| np.var | np.nanvar | 计算元素的方差 |
| np.min | np.nanmin | 找出最小值 |
| np.max | np.nanmax | 找出最大值 |
| np.argmin | np.nanargmin | 找出最小值的索引 |
| np.argmax | np.nanargmax | 找出最大值的索引 |
| np.median | np.nanmedian | 计算元素的中位数 |
| np.percentile | np.nanpercentile | 计算基于元素排序的统计值 |
| np.any | N/A | 验证任何一个元素是否为真 |
| np.all | N/A | 验证所有元素是否为真 |