# 2.6.2 和通用函数蕾丝的比较操作

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
x < 3 # 小于

array([ True,  True, False, False, False])

In [3]:
x > 3 # 大于

array([False, False, False,  True,  True])

In [4]:
x <= 3 # 小于等于

array([ True,  True,  True, False, False])

In [5]:
x >= 3 # 大于等于

array([False, False,  True,  True,  True])

In [6]:
x != 3 # 不等于

array([ True,  True, False,  True,  True])

In [7]:
x == 3 # 等于

array([False, False,  True, False, False])

In [8]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

比较运算符对应的通用函数

| 运算符 | 对应的通用函数 |
| --- | --- |
| == | np.equal |
| != | np.not_equal |
| < | np.less |
| <= | np.less_equal |
| > | np.greater |
| >= | np.greater_equal |

和算术运算通用函数一样，比较运算通用函数也可以用于任意形状、大小的数组。

In [9]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [10]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

# 2.6.3 操作布尔数组

In [11]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

## 1. 统计记录的个数

In [12]:
np.count_nonzero(x < 6)

8

In [13]:
np.sum(x < 6)

8

In [14]:
np.sum(x < 6, axis=1) # 每行有多少个值小于6

array([4, 2, 2])

In [15]:
np.any(x > 8) # 有没有值大于8

True

In [16]:
np.any(x < 0) # 有没有值小于0

False

In [17]:
np.all(x < 10) # 是不是所有的值都小于10

True

In [18]:
np.all(x == 6) # 是不是所有的值都等于6

False

In [19]:
np.all(x < 8, axis=1) # 是否每行的所有值都小于8

array([ True, False,  True])

## 2. 布尔运算符

| 运算符 | 对应通用函数 |
| --- | --- |
| & | np.bitwise_and |
| \| | np.bitwise_or |
| ^ | np.bitwise_xor |
| ~ | np.bitwise_not |

# 2.6.4 将布尔数组作为掩码

In [20]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [21]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [22]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

**and和or判断整个对象是真是假，而&和|是指每个对象中的比特位**