In [1]:
import torch

# 连接操作

## cat

In [2]:
A = torch.ones(3, 3)
B = 2 * torch.ones(3, 3)

In [3]:
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
B

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [5]:
C = torch.cat((A, B), 0)
C

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
D = torch.cat((A, B), 1)
D

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])

## stack

In [7]:
A = torch.arange(0, 4)
A

tensor([0, 1, 2, 3])

In [8]:
B = torch.arange(5, 9)
B

tensor([5, 6, 7, 8])

In [9]:
C = torch.stack((A, B), 0)
C

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [10]:
D = torch.stack((A, B), 1)
D

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])

# 切分

## chunk

torch.chunk(input, chunks, dim=0) # 参数chunks必须是整数

In [11]:
A = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [12]:
B = torch.chunk(A, 2, 0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

如果chunk参数不能够整除的话

In [13]:
B = torch.chunk(A, 3, 0) # 4, 4, 2
B

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))

In [14]:
A = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17])
B = torch.chunk(A, 4, 0)
B

(tensor([1, 2, 3, 4, 5]),
 tensor([ 6,  7,  8,  9, 10]),
 tensor([11, 12, 13, 14, 15]),
 tensor([16, 17]))

切分成了 5, 5, 5, 2 长度的向量，由此可见chunk是除法，然后向上取整

In [15]:
A = torch.tensor([1, 2, 3])
B = torch.chunk(A, 5, 0)
B

(tensor([1]), tensor([2]), tensor([3]))

chunk参数大于可切分的长度，则会切分成若干个长度为1的向量

In [16]:
A = torch.ones(4, 4)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
B = torch.chunk(A, 2, 0)
B

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [18]:
B = torch.chunk(A, 2, 1)
B

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]))

## split

In [19]:
A = torch.rand(4, 4)
A

tensor([[0.3504, 0.4690, 0.7019, 0.3637],
        [0.0179, 0.7827, 0.0201, 0.9353],
        [0.1845, 0.8688, 0.4819, 0.3600],
        [0.1376, 0.8005, 0.0161, 0.4226]])

In [20]:
B = torch.split(A, 2, 0)
B

(tensor([[0.3504, 0.4690, 0.7019, 0.3637],
         [0.0179, 0.7827, 0.0201, 0.9353]]),
 tensor([[0.1845, 0.8688, 0.4819, 0.3600],
         [0.1376, 0.8005, 0.0161, 0.4226]]))

In [21]:
C = torch.split(A, 3, 0)
C

(tensor([[0.3504, 0.4690, 0.7019, 0.3637],
         [0.0179, 0.7827, 0.0201, 0.9353],
         [0.1845, 0.8688, 0.4819, 0.3600]]),
 tensor([[0.1376, 0.8005, 0.0161, 0.4226]]))

In [22]:
A = torch.rand(5, 4)
A

tensor([[0.3079, 0.8712, 0.4690, 0.8309],
        [0.0220, 0.3333, 0.2251, 0.2998],
        [0.5099, 0.0215, 0.7324, 0.3560],
        [0.3715, 0.1841, 0.1934, 0.3877],
        [0.0114, 0.7080, 0.4150, 0.8662]])

In [23]:
B = torch.split(A, (2, 3), 0)
B

(tensor([[0.3079, 0.8712, 0.4690, 0.8309],
         [0.0220, 0.3333, 0.2251, 0.2998]]),
 tensor([[0.5099, 0.0215, 0.7324, 0.3560],
         [0.3715, 0.1841, 0.1934, 0.3877],
         [0.0114, 0.7080, 0.4150, 0.8662]]))

## unbind

In [24]:
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [25]:
B = torch.unbind(A, 0)
B

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]))

In [26]:
B = torch.unbind(A, 1)
B

(tensor([ 0,  4,  8, 12]),
 tensor([ 1,  5,  9, 13]),
 tensor([ 2,  6, 10, 14]),
 tensor([ 3,  7, 11, 15]))

# 索引操作

## index_select

In [27]:
A = torch.arange(0, 16).view(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [28]:
B = torch.index_select(A, 0, torch.tensor([1, 3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [29]:
C = torch.index_select(A, 1, torch.tensor([0, 3]))
C

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

## masked_select

In [30]:
A = torch.rand(5)
A

tensor([0.4268, 0.0570, 0.9600, 0.8050, 0.7806])

In [31]:
B = A > 0.3
B

tensor([ True, False,  True,  True,  True])

In [32]:
C = torch.masked_select(A, B)
C

tensor([0.4268, 0.9600, 0.8050, 0.7806])

可以简化为：

In [33]:
A = torch.rand(5)
A

tensor([0.1448, 0.3676, 0.3988, 0.5029, 0.6017])

In [34]:
C = torch.masked_select(A, A > 0.3)
C

tensor([0.3676, 0.3988, 0.5029, 0.6017])