In [1]:
import torch

In [2]:
torch.tensor(10)

tensor(10)

In [3]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
a = torch.Tensor(1)
b = a.item()

In [7]:
b

7.006492321624085e-45

In [8]:
a = [1, 2, 3]
b = torch.Tensor(a)
c = b.numpy().tolist()

In [9]:
c

[1.0, 2.0, 3.0]

In [10]:
a = torch.zeros(2, 3, 5)
a.shape

torch.Size([2, 3, 5])

In [11]:
a.size()

torch.Size([2, 3, 5])

In [12]:
a.numel()

30

# 矩阵转秩（维度转换）

In [23]:
x = torch.rand(2, 3, 5)
x.shape

torch.Size([2, 3, 5])

In [24]:
x = x.permute(2, 1, 0)
x.shape

torch.Size([5, 3, 2])

In [25]:
y = torch.rand(2, 3, 4)
y.shape

torch.Size([2, 3, 4])

In [26]:
y = y.transpose(1, 0)
y.shape

torch.Size([3, 2, 4])

# 形状变换

In [27]:
x = torch.randn(4, 4)
x.shape

torch.Size([4, 4])

In [28]:
x = x.view(2, 8)
x.shape

torch.Size([2, 8])

In [29]:
x = x.permute(1, 0)
x.shape

torch.Size([8, 2])

In [34]:
# x.view(4, 4)
# 内存不连续Tensor的结构，会报错

In [35]:
x = x.reshape(4, 4)
x.shape

torch.Size([4, 4])

# 增减维度

In [36]:
x = torch.rand(2, 1, 3)
x.shape

torch.Size([2, 1, 3])

In [38]:
y = x.squeeze(1)
y.shape

torch.Size([2, 3])

In [39]:
z = y.squeeze(1)
z.shape

torch.Size([2, 3])

In [40]:
x = torch.rand(2, 1, 3)
y = x.unsqueeze(2)
y.shape

torch.Size([2, 1, 1, 3])