In [1]:
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor
    def __len__(self):
        return self.data_tensor.size(0)
    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]

In [2]:
data_tensor = torch.randn(10, 3)
target_tensor = torch.randint(2, (10, )) # 标签是0或1

my_dataset = MyDataset(data_tensor, target_tensor)

print('Dataset size:', len(my_dataset))

print('tensor_data[0]:', my_dataset[0])

Dataset size: 10
tensor_data[0]: (tensor([0.2468, 1.2107, 1.2300]), tensor(0))


## DataLoader类的调用：

In [3]:
from torch.utils.data import DataLoader

tensor_dataloader = DataLoader(dataset=my_dataset,
                               batch_size=2,
                               shuffle=True,
                               num_workers=0)

for data, target in tensor_dataloader:
    print(data, target)
    
print('One batch tensor data: ', iter(tensor_dataloader).next())

tensor([[ 0.2468,  1.2107,  1.2300],
        [ 0.8935, -0.3969,  0.4230]]) tensor([0, 0])
tensor([[-0.6713, -1.4695, -0.3657],
        [-0.1613,  2.2772,  0.9263]]) tensor([1, 0])
tensor([[-0.4203, -0.8637, -0.4272],
        [ 0.8247, -0.1206,  0.7929]]) tensor([0, 0])
tensor([[ 0.0075,  1.0214, -0.8051],
        [ 0.0560,  0.8534, -0.4892]]) tensor([1, 1])
tensor([[-1.3325,  0.1837,  0.1072],
        [-0.2840, -0.4770, -0.3373]]) tensor([0, 1])
One batch tensor data:  [tensor([[-0.2840, -0.4770, -0.3373],
        [ 0.0075,  1.0214, -0.8051]]), tensor([1, 1])]


## torchvision

In [4]:
import torchvision

mnist_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=True, # True加载训练集，False加载测试集
                                           transform=None,
                                           target_transform=None,
                                           download=True)


In [5]:
type(mnist_dataset)

torchvision.datasets.mnist.MNIST

In [6]:
mnist_dataset_list = list(mnist_dataset)
# print(mnist_dataset_list)

In [7]:
display(mnist_dataset_list[0][0])
print("Image label is:", mnist_dataset_list[0][1])

Image label is: 5
